name: Refresh GitHub Streak Stats

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  refresh-streak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Touch README
        run: |
          git config --global user.name "YOUR_NAME"
          git config --global user.email "YOUR_EMAIL"
          git commit --allow-empty -m "Refresh streak stats"
          git push
